import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { db, pool } from './client.ts';

/**
 * Migrations are explicit SQL files under ./drizzle, generated by drizzle-kit
 * and committed to the repo. Schema is never pushed straight from the
 * TypeScript definitions: a production database must always be migrated
 * through a reviewed, versioned, replayable path.
 */
await migrate(db, { migrationsFolder: './drizzle' });
console.log('migrations applied');
await pool.end();
