import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { db, pool } from './client.ts';

/**
 * Arbitrary but fixed: every instance of this service asks for the same lock,
 * and nothing else in the database uses this number.
 */
const MIGRATION_LOCK_ID = 40172026;

/**
 * Migrations are explicit SQL files under ./drizzle, generated by drizzle-kit
 * and committed to the repo. Schema is never pushed straight from the
 * TypeScript definitions: a production database must always be migrated
 * through a reviewed, versioned, replayable path.
 *
 * The whole thing runs under an advisory lock because a deploy starts every
 * replica at once, and they all run this. Postgres DDL is not concurrency
 * safe — even `create schema if not exists` raises a duplicate key error when
 * two sessions execute it at the same instant — so without the lock most of
 * the replicas crash on boot and rely on being restarted. With it, one
 * migrates while the others wait, and then find there is nothing to do.
 *
 * The lock is held on a session, so it is released even if this process is
 * killed partway through.
 */
const client = await pool.connect();
try {
  await client.query('select pg_advisory_lock($1)', [MIGRATION_LOCK_ID]);
  await migrate(db, { migrationsFolder: './drizzle' });
  console.log('migrations applied');
} finally {
  await client.query('select pg_advisory_unlock($1)', [MIGRATION_LOCK_ID]);
  client.release();
}

await pool.end();
